//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::notif_subs::Entity as NotifSubs;
pub use super::notifs::Entity as Notifs;
pub use super::tags::Entity as Tags;
pub use super::tasks::Entity as Tasks;
pub use super::users::Entity as Users;
